SP19/Report/Controllers/AssignGiftMegaController.cs
using Business;
using Report.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Report.Models;
using System.Text;
using System.Web.UI;

namespace Report.Controllers
{
    public class AssignGiftMegaController : BaseController
    {
        //
        // GET: /Notification/
        // phân quà mega trúng cho siêu thị
        public ActionResult Index()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                string Message = String.Empty;
                Outlet outlet = new Outlet();
                LuckyAssignSE se = new LuckyAssignSE();
                Lucky_Mega_Gift gift = new Lucky_Mega_Gift();
                Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
                //get outlet
                SelectList listOutlet = new SelectList(outlet.GetAllForComboMega(User.ProjectID, User.OutletTypeID), "ID", "Text");
                ViewBag.listOutlet = listOutlet;
                //quà
                SelectList listGift = new SelectList(gift.GetAllForComboMega(DateTime.Now), "ID", "Text");
                ViewBag.listGift = listGift;
                //đợt
                SelectList listTurn = new SelectList(gift.GetTurn(DateTime.Now), "ID", "Text");
                ViewBag.listturn = listTurn;
                //danh sách outlet Mega     
                List<LuckyAssignEXT> listgiftoutlet = Lucky_Mega_Set_Gift_To_Outlet.GetAllMega(DateTime.Now,User.ProjectID, User.OutletTypeID);               
                return View(listgiftoutlet);
            }
        }
        public ActionResult _Search()
        {
            LuckyAssignSE se = new LuckyAssignSE();
            return PartialView();
        }     
        public ActionResult AddNew( string _date, string _outletassign, string _gift)
        {
            if (User != null)
            {
                Outlet outlet = new Outlet();
                LuckyAssignSE se = new LuckyAssignSE();
                Lucky_Mega_Gift gift = new Lucky_Mega_Gift();
                string _messageSystemError = String.Empty;
                Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
                List<Lucky_Mega_Set_Gift_To_Outlet> list = new List<Lucky_Mega_Set_Gift_To_Outlet>();
                Common.ERROR_CODE.ERROR_CODE_ITEMS_ADDNEW errCode = Lucky_Mega_Set_Gift_To_Outlet.AddNew(ref _messageSystemError, _date, _outletassign, _gift, User.UserID);
                List<LuckyAssignEXT> listgiftoutlet = Lucky_Mega_Set_Gift_To_Outlet.GetAllMega(Common.ConvertUtils.ConvertStringToShortDate(_date), User.ProjectID, User.OutletTypeID);
                //return PartialView("_List", listgiftoutlet);
                //get outlet
                SelectList listOutlet = new SelectList(outlet.GetAllForComboMega(User.ProjectID, User.OutletTypeID), "ID", "Text");
                ViewBag.listOutlet = listOutlet;
                //quà
                SelectList listGift = new SelectList(gift.GetAllForComboMega(DateTime.Now), "ID", "Text");
                ViewBag.listGift = listGift;
                //đợt
                SelectList listTurn = new SelectList(gift.GetTurn(DateTime.Now), "ID", "Text");
                ViewBag.listturn = listTurn;
                var json = new { list1 = "Header", list2 = "Footer"};
                return CustomJson(json).AddPartialView("_Search").AddPartialView("_List", listgiftoutlet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Search(string _date, string _outletassign, string _gift)
        {
            if (User != null)
            {

                string _messageSystemError = String.Empty;
                Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
                List<Lucky_Mega_Set_Gift_To_Outlet> list = new List<Lucky_Mega_Set_Gift_To_Outlet>();
                LuckyAssignSE se = new LuckyAssignSE();
                se.DateAssignSE = Common.ConvertUtils.ConvertStringToShortDate(_date);
                se.OutletAssignSE = int.Parse(_outletassign);
                se.GiftSE = int.Parse(_gift);
                List<LuckyAssignEXT> listgiftoutlet = Lucky_Mega_Set_Gift_To_Outlet.Search(se, User.ProjectID, User.OutletTypeID);
                return PartialView("_List", listgiftoutlet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult SendOTP(string phone)
        {
            if (User != null)
            {

                string _messageSystemError = String.Empty;
                Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
                int _status = 0;
                var listgiftoutlet = Lucky_Mega_Set_Gift_To_Outlet.SendOTP(ref _messageSystemError, ref _status, phone, User.UserID);
                return Json(new { ok = _messageSystemError, status = _status }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Update(string _listID)
        {
            if (User != null)
            {

                string _messageSystemError = String.Empty;
                Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
                List<Lucky_Mega_Set_Gift_To_Outlet> list = new List<Lucky_Mega_Set_Gift_To_Outlet>();
                Common.ERROR_CODE.ERROR_CODE_ITEMS_UPDATE errCode = Lucky_Mega_Set_Gift_To_Outlet.Update(ref _messageSystemError, _listID, User.UserID);
                List<LuckyAssignEXT> listgiftoutlet = Lucky_Mega_Set_Gift_To_Outlet.GetAllMega(DateTime.Now, User.ProjectID, User.OutletTypeID);
                return PartialView("_List", listgiftoutlet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult SendNotification(string ID)
        {
            if (User != null)
            {

                string _messageSystemError = String.Empty;
                Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
                List<Lucky_Mega_Set_Gift_To_Outlet> list = new List<Lucky_Mega_Set_Gift_To_Outlet>();
                Common.ERROR_CODE.ERROR_CODE_ITEMS_UPDATE errCode = Lucky_Mega_Set_Gift_To_Outlet.SendMessage(ref _messageSystemError, ID, User.UserID);
                List<LuckyAssignEXT> listgiftoutlet = Lucky_Mega_Set_Gift_To_Outlet.GetAllMega(DateTime.Now, User.ProjectID, User.OutletTypeID);
                return PartialView("_List", listgiftoutlet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult GetGiftFordate(string _date, string _outletID)
        {
            if (User == null)
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string MessageError = String.Empty;
                Lucky_Mega_Gift gift = new Lucky_Mega_Gift();
                var listgift = gift.GetAllMega(Common.ConvertUtils.ConvertStringToShortDate(_date), _outletID);
                return Json(listgift, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult GetTurnFordate(string _date)
        {
            if (User == null)
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string MessageError = String.Empty;
                Lucky_Mega_Gift gift = new Lucky_Mega_Gift();
                var listTurn = gift.GetTurn(Common.ConvertUtils.ConvertStringToShortDate(_date));
                var listgift = gift.GetGift(Common.ConvertUtils.ConvertStringToShortDate(_date));
                return Json(new
                {
                    Turn = listTurn,
                    Gift = listgift
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult GetOutletNotGift(string _GiftID)
        {
            if (User == null)
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string MessageError = String.Empty;
                Lucky_Mega_Gift gift = new Lucky_Mega_Gift();
                var listOutlet = gift.GetOutletNotGift(_GiftID, User.ProjectID, User.OutletTypeID);
                return Json(listOutlet, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Login(string _phone, string _password)
        {
            Lucky_Mega_Set_Gift_To_Outlet giftoutlet = new Lucky_Mega_Set_Gift_To_Outlet();
            string MessageError = String.Empty;
            int status = 0;
            Outlet outlet = new Outlet();
            LuckyAssignSE se = new LuckyAssignSE();
            Lucky_Mega_Gift gift = new Lucky_Mega_Gift();
            Common.ERROR_CODE.ERROR_CODE_ITEMS_SELECT Error = giftoutlet.GetOPT(ref MessageError, _phone, _password, ref status);

SP19/Report/Views/AssignGiftMega/Index.cshtml
@model List<Business.LuckyAssignEXT>
@{
    ViewBag.Title = "Thiết Lập Quà Mega";
    Layout = "~/Views/Shared/_MegaLayout.cshtml";
}

<div id="loginassign">
    @{Html.RenderPartial("_LoginPage");}
</div>
<div id="assignsearch" style="display:none">
        @{Html.RenderPartial("_Search", new Business.LuckyAssignSE());}
    </div>

    <div id="listassign" style="display:none">
        @{Html.RenderPartial("_List", Model);}
    </div>

SP19/Report/Views/AssignGiftMega/_InfoCustomer.cshtml
@model List<Business.View_Customer_Gift_Mega>
@{
    ViewBag.Title = "KHÁCH HÀNG TRÚNG GIẢI";
}

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header" style="background-color:green">
            <h5 class="modal-title" id="exampleModalLabel" style="color: white">THÔNG TIN KHÁCH HÀNG</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-modal">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body" style="overflow:auto">
            <div class="w3-content w3-display-container" style="height: 400px; padding:0px!important">
                @{

                    if (Model.Count() > 0 || Model != null)
                    {
                        <p>
                            <i class="fa fa-check"></i>
                            Siêu Thị :<span style="color: red; font-size: large"> @Model.FirstOrDefault().OutletName</span>
                        </p>
                        foreach (var item in Model)
                        {

                            <div class="jumbotron" style="margin-bottom:0px">

                                <p>
                                    <i class="fa fa-check"></i>
                                    Mã Hóa Đơn :<span style="color: green; font-size: large"> @item.BillNumber</span>
                                </p>
                                <p>
                                    <i class="fa fa-check"></i>
                                    Tên Khách Hàng :<span style="color: green; font-size: large"> @item.CustomerName</span>
                                </p>
                                <p> SĐT : <span id="lat" style="color: green">@item.CustomerPhone</span></p>
                                <p>Giải Trúng : <span id="long" style="color:red">@item.Name</span></p>
                                <p>Thời Gian Quay Số : <span id="long" style="color: green">@item.DeviceDateTime.ToShortDateString()</span></p>
                                <p><img src="@item.Expr1" style="width:80px;height:100px" /></p>
                            </div>
                    <hr />
                        }
                    }
                }
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close-modal">Close</button>
        </div>
    </div>
</div>

SP19/Report/Views/AssignGiftMega/_List.cshtml
@model List<Business.LuckyAssignEXT>

@{
    ViewBag.Title = "Notification";
    string user = ViewBag.RoleUser;
    Layout = null;
}
<style>
    a:not([href]):not([tabindex]) {
        color: #10522b;
        text-decoration: underline;
        cursor: pointer;
    }
</style>

<div class="m-content" style="padding-top:0px;border-radius:10px">
    <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
        <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text" style="color:white">
                        Danh Sách Phân Quà
                    </h3>
                </div>
            </div>
        </div>

        <div class="m-portlet__body" style="overflow:auto">
            <table class="table table-striped new" id="m_table_notification">
                <thead style="background-color: #10522B; color: white; text-align: center">
                    <tr>
                        <th style="border: 1px solid #eee">Ngày Trúng</th>
                        <th style="border: 1px solid #eee">Siêu Thị</th>
                        <th style="border: 1px solid #eee">Quà</th>
                        <th style="border: 1px solid #eee">Trạng Thái</th>
                        <th style="border: 1px solid #eee">Gửi Thông Báo</th>
                        <th style="border: 1px solid #eee">Trúng Thưởng</th>
                       @* <th style="border: 1px solid #eee"><button type="button" style="background-color:red;color:white" class="btn btn-secondary" onclick="UpdateNotification()">Xóa</button></th>*@
                    </tr>
                </thead>
                <tbody style="color: white">
                    @{ foreach (var item in Model)
                     {
                        <tr>
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                            <td>@item.OutletName</td>
                            <td>@item.GiftName</td>
                            <td>
                                @{
                                     if (item.status != true)
                                     {
                                        <span class="m-badge m-badge--danger" style="font-size:large;padding:5px">CHƯA NHẬN</span>
                                     }
                                     else
                                     {
                                        <span class="m-badge m-badge--success" style="font-size: large; padding: 5px;background-color:green">ĐÃ NHẬN</span>
                                     }
                                }
                            </td>
                            <td>
                                @{
                                 if (item.status == false)
                                 {
                                    <a onclick="SendNotification(@item.ID)">Gửi</a>
                                 }
                                }
                            </td>
                            <td>
                                @{
                                     if (item.listgift != null && item.listgift.Count() > 0)
                                     {
                                        <a onclick="InfoCustomer('@item.OutletID','@item.listgift.FirstOrDefault().GiftID')"><span class="m-badge m-badge--success" style="font-size: large; padding: 5px;background-color:green">Thông Tin Trúng Giải</span></a>
                                     }
                                }
                            </td>
                            @*<td style="font-style: italic">
                                @{
                                     if (item.listgift == null || item.listgift.Count() == 0)
                                     {
                                        <input type="checkbox" name="idassign" value="@item.ID" />
                                     }
                                }
                            </td>*@
                        </tr>
                     }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    function getCheckedBoxes(chkboxName) {
        var checkboxes = document.getElementsByName(chkboxName);
        var checkboxesChecked = [];
        // loop over them all
        for (var i = 0; i < checkboxes.length; i++) {
            // And stick the checked ones onto an array...
            if (checkboxes[i].checked) {
                checkboxesChecked.push(checkboxes[i].value);
            }
        }
        // Return the array if it is non-empty, or null
        return checkboxesChecked.length > 0 ? checkboxesChecked : null;
    }

    function UpdateNotification() {
        debugger;
        var checkedBoxes = getCheckedBoxes("idassign").join('|');
        $('#myModal').modal('hide');
        $('#loadingmessage').show();
        $.ajax({
            url: "@Url.Action("Update", "AssignGiftMega")",
            type: 'GET',
            data: { _listID: checkedBoxes },
            contentType: 'application/json; charset=utf-8',
            datatype: 'html',
            success: function (result) {
                debugger;
                if (result.ok == false) {
                    window.location = result.newurl;
                }
                else {
                    $('#listassign').html(result);
                    $('#loadingmessage').hide();
                }

            }
        });
    }
    function SendNotification(ID) {
        debugger;
        $('#myModal').modal('hide');
        $('#loadingmessage').show();
        $.ajax({
            url: "@Url.Action("SendNotification", "AssignGiftMega")",
            type: 'GET',
            data: { ID: ID },
            contentType: 'application/json; charset=utf-8',
            datatype: 'html',
            success: function (result) {
                debugger;
                if (result.ok == false) {
                    window.location = result.newurl;
                }
                else {
                    alert("Thành Công");
                }

            }
        });
    }

    function InfoCustomer(_OutletID, _GiftID) {
        debugger;
        $.ajax({
            type: "GET",
            url: '@Url.Action("_InfoCustomer")',
            data: { _OutletID: _OutletID, _GiftID: _GiftID },
            datatype: "image/jpg",
            success: function (data) {
                $('#myModal').empty();
                $('#myModal').append(data);
                $('#myModal').modal('show');
            }
        });
    }
</script>

SP19/Report/Views/AssignGiftMega/_LoginPage.cshtml
@{
    Layout = null;
    string company = ViewBag.company;
    string code = ViewBag.code;
    ViewBag.Title = "Thông Tin Nhân Viên";
}

<div class="m-login__signin">
    <div class="m-login__logo">
        <a href="#">
            <img src="~/Images/logo1.png" style="width: 300px; display: block; margin: auto; margin-top:5%" />  @*<img src="../../../assets/app/media/img//logos/logo-1.png">*@
        </a>
    </div>
    <form id="form1" runat="server" align="center">
        <div class="container" style=" position: absolute;  top: 50%;  left: 50%;  transform: translate(-50%, -50%);">
            <div class="main" style="min-width:300px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">

                <form id="form_id" method="post" name="myform">
                    <div class="input-group">
                        
                        <input type="text" style=" border-radius: 0px; border: 1px solid green; padding: 1.5rem 1.5rem; margin-top: 1.5rem; color: green;" name="phone" id="phone" class="form-control m-input" placeholder="Số Điện Thoại">
                        <span class="input-group-btn">
                            <button style=" border-radius: 0px; border: 1px solid green; padding: 1.5rem 1.5rem; margin-top: 1.5rem; color: green;" class=" btn btn-default" type="button" onclick="sendotp();">Nhận Mã OTP</button>
                        </span>
                    </div>
                    <input type="password" style=" border-radius: 0px; border: 1px solid green; padding: 1.5rem 1.5rem; margin-top: 1.5rem; color: green; display:none" name="password" id="password" class="form-control m-input" onkeypress="return runScript(event)" placeholder="Mật Khẩu" width="100px" />
                    <input type="button" value="Đăng Nhập" id="submit" onclick="validate();" style="color: white; font-family: Arial !important; font-size: 14px; display: inline-block; text-align: center; padding: 1.4rem 4rem; margin-top: 2.8rem; border-radius: inherit; background-color: #004910; border: 1px solid #004910 !important; box-shadow: 0 5px 10px 2px rgba(152,22,244,.19) !important; " />
                </form>
            </div>
            <div id="result" style="width: 400px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);margin-top:45px;color:red">
                @{Html.RenderPartial("_Result");}
            </div>
        </div>
    </form>
</div>
<script language="JavaScript">
    $('#logo').css("display", "none");
    function runScript(e) {
        //See notes about 'which' and 'key'
        if (e.keyCode == 13) {
            validate()
            return false;
        }
    }
    function validate() {
        var phone = document.getElementById("phone").value;
        var password = document.getElementById("password").value;
        if (phone == "" || password == "") {
            alert("Vui Lòng Nhập Thông Tin Đầy Đủ.");
            return false;
        }
        debugger;
        $.ajax({

            url: "@Url.Action("Login")",
            type: 'POST',
            data: { _phone: phone, _password: password },
            datatype: 'json',
            success: function (data) {
                if (data.Json["list3"] == "2") {
                    $('#result').html(data.Html[1]);
                    $('#ketqua').css("display", "block");
                    $('#password').val("");
                }
                else {
                    $('#assignsearch').css("display", "block");
                    $('#listassign').css("display", "block");
                    $('#assignsearch').html(data.Html[0]);
                    $('#listassign').html(data.Html[2]);
                    $('#loginassign').css("display", "none");
                    $('#logo').css("display", "block");
                }
            },
            failure: function () {
                alert('Mật Khẩu Không Chính Xác!');
            }
        });
    }
    function sendotp() {
        var phone = document.getElementById("phone").value;
        if (phone == null || phone == "") {
            alert("Vui Lòng Nhập Thông Tin Đầy Đủ.");
            return false;
        }
        debugger;
        $.ajax({

            url: "@Url.Action("SendOTP")",
            type: 'POST',
            data: { phone: phone },
            datatype: 'json',
            success: function (data) {
                if (data.status == 1) {
                    $('#password').css("display", "block");
                    alert(data.ok);
                }
                else {
                    alert(data.ok);
                }
            }
        });
    }
</script>

SP19/Report/Views/AssignGiftMega/_Result.cshtml
@{
    Layout = null;
}

<h5 style="color: red;display:none" id="ketqua">Vui Lòng Đăng Nhập Đúng Để Thấy Thông Tin</h5>

SP19/Report/Views/AssignGiftMega/_Search.cshtml
@model Business.LuckyAssignSE

<div class="m-content">
    <div class="row">
        <div class="col-md-12">
            <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
                <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text" style="color:white">
                                Thông Tin Phân Quà
                            </h3>
                        </div>
                    </div>
                </div>
                <form class="m-form m-form--fit m-form--label-align-right">
                    <div class="m-portlet__body">
                        <div class="form-group m-form__group">
                            @Html.LabelFor(m => m.DateAssignSE)
                            @Html.TextBoxFor(m => m.DateAssignSE, "{0:dd/MM/yyyy}", new { style = "width:100%", @Value = DateTime.Now.ToString("dd/MM/yyyy") })
                        </div>
                        <div class="form-group m-form__group">
                            @Html.LabelFor(m => m.TurnSE)
                            @Html.DisplayFor(m => m.TurnSE)
                        </div>
                      
                    </div>
                    <div class="m-portlet__body">
                        <div class="form-group m-form__group">
                            @Html.LabelFor(m => m.GiftSE)
                            @Html.DisplayFor(m => m.GiftSE)
                        </div>
                        <div class="form-group m-form__group">
                            @Html.LabelFor(m => m.OutletAssignSE)
                            @Html.DisplayFor(m => m.OutletAssignSE)
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <button type="button" style="background-color: #10522B;color:white" class=  "btn btn-success" onclick="AddAssignGift()">Xác Nhận</button>
                            <button type="button" style="background-color: #10522B;color:white" class="btn btn-success" onclick="SearchAssignGift()">Tìm Kiếm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $(".chosen-select").chosen();
        $(".chosen-container").css("width", "100%");
        $(".chosen-container").css("height", "30px!important");
    });
</script>

<script>
    $("#DateAssignSE").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy'
    });
</script>
<script>
    $("#GiftSE").change(function () {
        debugger;
        var selectedId = $("#GiftSE").val();
        $.ajax({
            url: "@Url.Action("GetOutletNotGift")",
            type: 'GET',
            data: { _GiftID: selectedId },
            contentType: 'application/json; charset=utf-8',
            success: function (teamdailyse) {
                debugger;
                if (teamdailyse.ok == false) {
                    window.location = teamdailyse.newurl;
                }
                else {
                    $('#OutletAssignSE option').remove();
                    for (var i = 0; i < teamdailyse.length; i++) {
                        $("#OutletAssignSE").append("<option value=" + " " + teamdailyse[i].ID + " " + ">" + teamdailyse[i].Text + "</option>");
                        $('#OutletAssignSE').trigger("chosen:updated");
                    }
                }
            }
        });
    });
    $("#DateAssignSE").change(function () {
        debugger;
        var selectedId = $("#DateAssignSE").val();
        $.ajax({
            url: "@Url.Action("GetTurnFordate")",
            type: 'GET',
        data: { _date: selectedId },
        contentType: 'application/json; charset=utf-8',
        success: function (teamdailyse) {
            debugger;
            if (teamdailyse.ok == false) {
                window.location = teamdailyse.newurl;
            }
            else {
                $('#TurnSE option').remove();
                for (var i = 0; i < teamdailyse.Turn.length; i++) {
                    $("#TurnSE").append("<option value=" + " " + teamdailyse.Turn[i].ID + " " + ">" + teamdailyse.Turn[i].Text + "</option>");
                    $('#TurnSE').trigger("chosen:updated");
                }
                $('#GiftSE option').remove();
                for (var i = 0; i < teamdailyse.Gift.length; i++) {
                    $("#GiftSE").append("<option value=" + " " + teamdailyse.Gift[i].ID + " " + ">" + teamdailyse.Gift[i].Text + "</option>");
                    $('#GiftSE').trigger("chosen:updated");
                }
            }
        }
    });
    });

    function SearchAssignGift() {
        var _date = $("#DateAssignSE").val();
        var _outletassign = $("#OutletAssignSE option:selected").val();
        var _gift = $("#GiftSE option:selected").val();
        $('#loadingmessage').show();
        $.ajax({
            url: "@Url.Action("Search", "AssignGiftMega")",
            type: 'GET',
            data: { _date: _date, _outletassign: _outletassign, _gift: _gift },
            contentType: 'application/json; charset=utf-8',
            datatype: 'html',
            success: function (result) {
                debugger; if (result.ok == false) {
                    window.location = result.newurl;
                }
                else {
                    $('#listassign').html(result);
                    $('#loadingmessage').hide();
                }
            }
        });
    }
    function AddAssignGift() {
        var _date = $("#DateAssignSE").val();
        var _outletassign = $("#OutletAssignSE option:selected").val();
        var _gift = $("#GiftSE option:selected").val();
        $('#loadingmessage').show();
        if (_outletassign != "0" && _gift != "0") {
            $.ajax({
                url: "@Url.Action("AddNew", "AssignGiftMega")",
                type: 'GET',
                data: { _date: _date, _outletassign: _outletassign, _gift: _gift },
                contentType: 'application/json; charset=utf-8',
                datatype: 'html',
                success: function (result) {
                    debugger; if (result.ok == false) {
                        window.location = result.newurl;
                    }
                    else {
                        $('#assignsearch').html(result.Html[0]);
                        $('#listassign').html(result.Html[1]);
                        $('#loadingmessage').hide();
                        
                    }
                }
            });
        }
        else {
            alert("Vui Lòng Nhập Đầy Đủ Thông Tin Trước Khi Lưu!")
        }
    }
</script>