SP19/Report/Controllers/StockOfferManagerController.cs
using Business;
using Report.Helpers;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NPOI.HSSF.Util;
using Common;

namespace Report.Controllers
{
    public class StockOfferManagerController : BaseController
    {
        //
        // GET: /StockManager/
        // quản lý, đề xuất nhập hàng dựa theo báo cáo tồn kho 
        public ActionResult Index()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                    string _messageError = String.Empty;
                    Stock stock = new Stock();
                    List<StockEXT> list = new List<StockEXT>();
                    StockSE se = new StockSE();
                    //danh sach product
                    ViewBag.product = Business.Product.GetProduct(User.ProjectID);
                    ViewBag.outlets = Business.Outlet.GetAll(User.ProjectID, User.OutletTypeID);
                    ViewBag.havestatus = false;
                    //get outlet
                    Outlet outlet = new Outlet();
                    SelectList listOutlet = new SelectList(outlet.GetAllForCombo(User.ProjectID, User.OutletTypeID), "ID", "Text");
                    ViewBag.listOutlet = listOutlet;
                    //get sale 
                    Business.User user = new User();
                    SelectList listsale = new SelectList(user.GetUserSale(User.ProjectID, User.OutletTypeID), "ID", "Text");
                    ViewBag.listsale = listsale;
                    //get area 
                    Business.Region region = new Region();
                    SelectList listRegion = new SelectList(region.GetAllForCombo(User.ProjectID, User.OutletTypeID), "ID", "Text");
                    ViewBag.listRegion = listRegion;


                    //get district
                    SelectList listDistrict = new SelectList(region.GetDistrictForCombo(User.ProjectID, User.OutletTypeID), "ID", "Text");
                    ViewBag.listDistrict = listDistrict;

                    //get statusstock
                    CodeDetail codeDetail = new CodeDetail();
                    SelectList listStatusStock = new SelectList(codeDetail.GetForCombo("StatusStock"), "ID", "Text");
                    ViewBag.listStatusStock = listStatusStock;
                    ViewBag.UserRole = User.UserRoles.FirstOrDefault();
                    Common.ERROR_CODE.ERROR_CODE_ITEMS_SELECT error = stock.SearchOffer(ref _messageError, User.ProjectID, User.OutletTypeID, se, ref list);
                    return View(list);
            }
        }

        public JsonResult GetDistrictForRegion(string _RegionID)
        {
            if (User != null)
            {
                string messageSystemError = String.Empty;
                Team team = new Business.Team();
                var List = team.GetDistrictForRegion(_RegionID, User.ProjectID, User.OutletTypeID);
                return Json(List, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }

        //------------------------Get Outlet for district
        public JsonResult GetOutletForRegion(string _RegionID)
        {
            if (User != null)
            {

                string messageSystemError = String.Empty;
                Outlet outlet = new Business.Outlet();
                var List = outlet.GetOutletForRegion(_RegionID, User.ProjectID, User.OutletTypeID);
                return Json(List, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        } //------------------------Get Outlet for district
        public JsonResult GetSaleForRegion(string _RegionID)
        {
            if (User != null)
            {

                string messageSystemError = String.Empty;
                User user = new Business.User();
                var List = user.GetSaleForRegion(_RegionID, User.ProjectID, User.OutletTypeID);
                return Json(List, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }
        //------------------------Get Outlet for district
        public JsonResult GetOutletForSale(string _SaleID, string _RegionID)
        {
            if (User != null)
            {

                string messageSystemError = String.Empty;
                Outlet outlet = new Business.Outlet();
                var List = outlet.GetOutletForSale(int.Parse(_SaleID), _RegionID, User.ProjectID, User.OutletTypeID);
                return Json(List, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetOutletForDistrict(string _DistrictID)
        {
            if (User != null)
            {
                string messageSystemError = String.Empty;
                Outlet outlet = new Business.Outlet();
                var List = outlet.GetOutletForDistrict(int.Parse(_DistrictID), User.ProjectID, User.OutletTypeID);
                return Json(List, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { ok = false, newurl = Url.Action("Login", "Account") }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Search(int? page,string _DistrictAttendance, string _RegionStockSE, string _OutletStockSE, string _StatusStockSE, string _DateStockSE,string _SaleID)
        {

            string _messageError = String.Empty;
            Stock stock = new Stock();
            List<StockEXT> list = new List<StockEXT>();
            StockSE se = new StockSE();
            ViewBag.product = Business.Product.GetProduct(User.ProjectID);
            ViewBag.outlets = Business.Outlet.SearchOutlet(int.Parse(_DistrictAttendance??"0"), User.ProjectID, User.OutletTypeID, int.Parse(_OutletStockSE), _RegionStockSE, _SaleID);
            if (_StatusStockSE == "0")
            {
                ViewBag.havestatus = false;
            }
            else
            {
                ViewBag.havestatus = true;
            }
            se.DateStockSE = Common.ConvertUtils.ConvertStringToShortDate(_DateStockSE);
            se.OutletStockSE = int.Parse(_OutletStockSE);
            se.DistrictAttendance = int.Parse(_DistrictAttendance);
            se.RegionStockSE = _RegionStockSE;
            se.StatusStockSE = long.Parse(_StatusStockSE);
            se.SaleSE = long.Parse(_SaleID);
            Session["DateStockSE"] = _DateStockSE;
            Session["OutletStockSE"] = se.OutletStockSE;
            Session["RegionStockSE"] = se.RegionStockSE;
            Session["StatusStockSE"] = se.StatusStockSE;
            Session["SaleSE"] = se.SaleSE;
            Session["DistrictAttendanceOffer"] = se.DistrictAttendance;
            Common.ERROR_CODE.ERROR_CODE_ITEMS_SELECT error = stock.SearchOffer(ref _messageError, User.ProjectID, User.OutletTypeID, se, ref list);
            ViewBag.UserRole = User.UserRoles.FirstOrDefault();
            return PartialView("_List", list);
        }
       

       
        public ActionResult TimeOut()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                return View();
            }
        }
    }
}

SP19/Report/Views/StockOfferManager/Index.cshtml
@model List<Business.StockEXT>

@{
    ViewBag.Title = "ĐỀ NGHỊ KHO";
}

@{Html.RenderPartial("_Search", new Business.StockSE());}
<div class="m-content" style="overflow: auto; display: none">
    <div class="col-md-12">
        <table class="table" style="width: 100%">
            <tr>
                <td style="padding: 0px; border-top: none!important">
                    <table>
                        <tr>
                            <td style="color: white">GROUP 1</td>
                            <td style="color: red">OOS</td>
                            <td style="color: #ffd700">URGENT</td>
                            <td style="color: green">SAFETY</td>
                        </tr>
                        <tr>
                            <td style="color: white">Hei Regular 24s </td>
                            <td style="color: red"> 0-500</td>
                            <td style="color: #ffd700; ">501 - 1000</td>
                            <td style="color: green"> 1000</td>
                        </tr>
                        <tr>
                            <td style="color: white">Tiger regular 24s</td>
                            <td style="color: red"> 0-500</td>
                            <td style="color: #ffd700; ">501 - 1000</td>
                            <td style="color: green"> 1000</td>
                        </tr>
                        <tr>
                            <td style="color: white"> Hei Sleek 24s</td>
                            <td style="color: red"> 0-80</td>
                            <td style="color: #ffd700">81 - 120</td>
                            <td style="color: green"> > 120</td>
                        </tr>
                        <tr>
                            <td style="color: white"> Tiger Crystal 24s</td>
                            <td style="color: red"> 0-80</td>
                            <td style="color: #ffd700">81 - 120</td>
                            <td style="color: green"> > 120</td>
                        </tr>
                        <tr>
                            <td style="color: white; ">Larue Blue</td>
                            <td style="color: red"> 0-10</td>
                            <td style="color: #ffd700">11 - 15</td>
                            <td style="color: green"> >15</td>
                        </tr>
                        <tr>
                            <td style="color: white; ">Larue Special</td>
                            <td style="color: red"> 0-5</td>
                            <td style="color: #ffd700">6 - 10</td>
                            <td style="color: green"> >10</td>
                        </tr>
                        <tr>
                            <td style="color: white">Strongbow 8s </td>
                            <td style="color: red"> 0-50</td>
                            <td style="color: #ffd700">51 - 80</td>
                            <td style="color: green"> >80</td>
                        </tr>
                        <tr>
                            <td style="color: white">Strongbow 24s</td>
                            <td style="color: red"> 0-10</td>
                            <td style="color: #ffd700">11 - 15</td>
                            <td style="color: green"> >15</td>
                        </tr>
                    </table>

                </td>
                <td style="padding: 0px; border-top: none!important">
                    <table>
                        <tr>
                            <td style="color: white">GROUP 2</td>
                            <td style="color: red">OOS</td>
                            <td style="color: #ffd700">URGENT</td>
                            <td style="color: green">SAFETY</td>
                        </tr>
                        <tr>
                            <td style="color: white">Hei Regular 24s</td>
                            <td style="color: red"> 0-120</td>
                            <td style="color: #ffd700">121 - 240</td>
                            <td style="color: green"> >240</td>
                        </tr>
                        <tr>
                            <td style="color: white"> Tiger regular 24s</td>
                            <td style="color: red"> 0-120</td>
                            <td style="color: #ffd700">121 - 240</td>
                            <td style="color: green"> >240</td>
                        </tr>
                        <tr>
                            <td style="color: white"> Hei Sleek 24s</td>
                            <td style="color: red"> 0-9</td>
                            <td style="color: #ffd700">10 - 19</td>
                            <td style="color: green"> > 20</td>
                        </tr>
                        <tr>
                            <td style="color: white"> Tiger Crystal 24s</td>
                            <td style="color: red"> 0-9</td>
                            <td style="color: #ffd700">10 - 19</td>
                            <td style="color: green"> > 20</td>
                        </tr>
                        <tr>
                            <td style="color: white">Larue Blue</td>
                            <td style="color: red"> 0-5</td>
                            <td style="color: #ffd700">6 - 10</td>
                            <td style="color: green"> >10</td>
                        </tr>
                        <tr>
                            <td style="color: white">Larue Special</td>
                            <td style="color: red"> 0-5</td>
                            <td style="color: #ffd700">6 - 10</td>
                            <td style="color: green"> >10</td>
                        </tr>
                        <tr>
                            <td style="color: white; ">Strongbow 8s </td>
                            <td style="color: red"> 0-30</td>
                            <td style="color: #ffd700">31 - 50</td>
                            <td style="color: green"> >50</td>
                        </tr>
                        <tr>
                            <td style="color: white">Strongbow 24s</td>
                            <td style="color: red"> 0-5</td>
                            <td style="color: #ffd700">6 - 10</td>
                            <td style="color: green"> >10</td>
                        </tr>
                    </table>

                </td>
                <td style="padding: 0px; border-top: none!important">
                    <table>
                        <tr>
                            <td style="color: white">GROUP 3</td>
                            <td style="color: red">OOS</td>
                            <td style="color: #ffd700">URGENT</td>
                            <td style="color: green">SAFETY</td>
                        </tr>
                        <tr>
                            <td style="color: white">Hei Regular 24s</td>
                            <td style="color: red"> 0-10</td>
                            <td style="color: #ffd700; ">11 - 15</td>
                            <td style="color: green"> >15</td>
                        </tr>
                        <tr>
                            <td style="color: white">Tiger regular 24s</td>
                            <td style="color: red"> 0-10</td>
                            <td style="color: #ffd700; ">11 - 15</td>
                            <td style="color: green"> >15</td>
                        </tr>
                        <tr>
                            <td style="color: white"> Tiger Crystal 24s,Larue Blue</td>
                            <td style="color: red"> 0-5</td>
                            <td style="color: #ffd700">6 - 10</td>
                            <td style="color: green"> > 10</td>
                        </tr>
                        <tr>
                            <td style="color: white">Larue Blue</td>
                            <td style="color: red"> 0-5</td>
                            <td style="color: #ffd700">6 - 10</td>
                            <td style="color: green"> > 10</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
</div>
<div id='loadingmessage' style='display:none; text-align: -webkit-center;'>
    <img src="~/Images/process.gif" class="loader"  />
</div>
<div id="liststockoffermanager">
    @{Html.RenderPartial("_List", Model);}
</div>

SP19/Report/Views/StockOfferManager/TimeOut.cshtml
@{
    ViewBag.Title = "TimeOut";
}

<img src="~/Images/alert.png" /> <h1 style="color:white">Phiên làm việc đã hết!</h1>
<h2 style="color:yellow">Vui lòng kiểm tra và cập nhật thông tin từ 10:01 đến 14:00 mỗi ngày!</h2>

SP19/Report/Views/StockOfferManager/_Search.cshtml
@model Business.StockSE

<div class="m-content">
    <div class="row">
        <div class="col-md-12">
            <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
                <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text" style="color:white">
                                Nội Dung Tìm Kiếm
                            </h3>
                        </div>
                    </div>
                </div>
                <form class="m-form m-form--fit m-form--label-align-right">
                    <div class="m-portlet__body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-form__group" style="padding-bottom: 0px!important">
                                    @Html.LabelFor(m => m.DateStockSE)
                                    @Html.TextBoxFor(m => m.DateStockSE, "{0:dd/MM/yyyy}", new { style = "width:100%" })
                                </div>
                                <div class="form-group m-form__group">
                                    @Html.LabelFor(m => m.SaleSE)
                                    @Html.DisplayFor(m => m.SaleSE)
                                </div>

                            </div>
                            <div class="col-md-6" style="margin-top: 0px!important;">
                                <div class="form-group m-form__group" style="padding-bottom: 0px!important">
                                    @Html.LabelFor(m => m.RegionStockSE)
                                    @Html.DisplayFor(m => m.RegionStockSE)
                                </div>
                                <div class="form-group m-form__group">
                                    @Html.LabelFor(m => m.DistrictAttendance)
                                    @Html.DisplayFor(m => m.DistrictAttendance)
                                </div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-form__group" style="margin-top: 15px;">
                                    @Html.LabelFor(m => m.StatusStockSE)
                                    @Html.DisplayFor(m => m.StatusStockSE)
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group" style="margin-top: 15px;">
                                    @Html.LabelFor(m => m.OutletStockSE)
                                    @Html.DisplayFor(m => m.OutletStockSE)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <button type="button" style="background-color: #10522B;color:white" class="btn btn-success" onclick="SearchStock()">Tìm Kiếm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $("#DateStockSE").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy'
    });
</script>
<script>
    $("#DistrictAttendance").change(function () {
        var selectedId = $("#DistrictAttendance").val();
        $.ajax({
            url: "@Url.Action("GetOutletForDistrict")",
            type: 'GET',
        data: { _DistrictID: selectedId},
        contentType: 'application/json; charset=utf-8',
        success: function (teamdailyse) {
            debugger; if (teamdailyse.ok == false) {
                window.location = teamdailyse.newurl;
            } else {
                $('#OutletStockSE option').remove();
                for (var i = 0; i < teamdailyse.length; i++) {
                    $("#OutletStockSE").append("<option value=" + " " + teamdailyse[i].ID + " " + ">" + teamdailyse[i].Text + "</option>");
                    $('#OutletStockSE').trigger("chosen:updated");
                }
            }
        }
    });
    });
        $("#RegionStockSE").change(function () {
        var selectedId = $("#RegionStockSE option:selected").text();
        $.ajax({
            url: "@Url.Action("GetSaleForRegion")",
            type: 'GET',
            data: { _RegionID: selectedId },
            contentType: 'application/json; charset=utf-8',
            success: function (teamdailyse) {
                debugger; if (teamdailyse.ok == false) {
                    window.location = teamdailyse.newurl;
                } else {
                    $('#SaleSE option').remove();
                    for (var i = 0; i < teamdailyse.length; i++) {
                        $("#SaleSE").append("<option value=" + " " + teamdailyse[i].ID + " " + ">" + teamdailyse[i].Text + "</option>");
                        $('#SaleSE').trigger("chosen:updated");
                    }
                }
            }
        });
            $.ajax({
                url: "@Url.Action("GetDistrictForRegion")",
                type: 'GET',
            data: { _RegionID: selectedId },
            contentType: 'application/json; charset=utf-8',
            success: function (teamdailyse2) {
                debugger;
                if (teamdailyse2.ok == false) {
                    window.location = teamdailyse2.newurl;
                }
                else {
                    $('#DistrictAttendance option').remove();
                    for (var i = 0; i < teamdailyse2.length; i++) {
                        $("#DistrictAttendance").append("<option value=" + " " + teamdailyse2[i].ID + " " + ">" + teamdailyse2[i].Text + "</option>");
                        $('#DistrictAttendance').trigger("chosen:updated");
                    }
                }
            }
        });
    });

    $("#SaleSE").change(function () {
        var selectedId = $("#SaleSE option:selected").val();
        var selectedRegionId = $("#RegionStockSE option:selected").text();
        $.ajax({
            url: "@Url.Action("GetOutletForSale")",
            type: 'GET',
            data: { _SaleID: selectedId, _RegionID: selectedRegionId },
        contentType: 'application/json; charset=utf-8',
        success: function (teamdailyse) {
            debugger; if (teamdailyse.ok == false) {
                window.location = teamdailyse.newurl;
            } else {
                $('#OutletStockSE option').remove();
                for (var i = 0; i < teamdailyse.length; i++) {
                    $("#OutletStockSE").append("<option value=" + " " + teamdailyse[i].ID + " " + ">" + teamdailyse[i].Text + "</option>");
                    $('#OutletStockSE').trigger("chosen:updated");
                }
            }
        }
    });
    });
    var x = 0;
    function SearchStock() {
        debugger
        var _DistrictAttendance = $("#DistrictAttendance").val();
        var _RegionStockSE = $("#RegionStockSE option:selected").text();
        var _DateStockSE = $("#DateStockSE").val();
        var _OutletStockSE = $("#OutletStockSE option:selected").val();
        var _StatusStockSE = $("#StatusStockSE option:selected").val();
        var _Sale = $("#SaleSE option:selected").val();
        $('#loading').css("display", "block");
        $.ajax({
            url: "@Url.Action("Search", "StockOfferManager")",
            type: 'GET',
            data: {_DistrictAttendance:_DistrictAttendance, _RegionStockSE: _RegionStockSE, _OutletStockSE: _OutletStockSE, _StatusStockSE: _StatusStockSE, _DateStockSE: _DateStockSE, _SaleID: _Sale },
            contentType: 'application/json; charset=utf-8',
            datatype: 'html',
            success: function (result) {
                debugger;
                $('#liststockoffermanager').html(result);
                $('#loading').css("display", "none");
            }
        });
    }
</script>