SP19/Report/Controllers/AddOutletTeamController.cs
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using Report.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using Business;
using Report.Models;
using NPOI.HSSF.Util;

namespace Report.Controllers
{
    // thêm outletteam
    public class AddOutletTeamController : BaseController
    {
        public ActionResult Index()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                AddOutletModel model = new AddOutletModel();
                model.status = 0;
                model.message = "";
                List<Outlet> listData = Outlet.GetAll(User.ProjectID, User.OutletTypeID);
                model.listData = listData;
                return View(model);
            }
        }

        public ActionResult ExportFormat()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                List<Chanel> listChanel = Chanel.getByProject(User.ProjectID);
                List<Region> listRegion = Region.getByProject(User.ProjectID);
                List<Group> listGroup = Group.getByProject(User.ProjectID);
                List<Brand> listBrand = Brand.getByProject(User.ProjectID);
                string _messageError = String.Empty;

                FileStream fs = new FileStream(Server.MapPath(@"~\ReportExcel\FormatOutlet.xls"), FileMode.Open, FileAccess.Read);
                HSSFWorkbook templateWorkbook = new HSSFWorkbook(fs, true);

                ICellStyle cellStyle = templateWorkbook.CreateCellStyle();
                ICellStyle cellStyle2 = templateWorkbook.CreateCellStyle();
                IDataFormat format = templateWorkbook.CreateDataFormat();
                cellStyle.DataFormat = format.GetFormat("dd/MM/yyyy HH:mm");
                cellStyle2.DataFormat = format.GetFormat("HH:mm:ss");


                HSSFCellStyle styleTitle = (HSSFCellStyle)templateWorkbook.CreateCellStyle();
                styleTitle.BorderTop = BorderStyle.Thin;
                styleTitle.BorderBottom = BorderStyle.Thin;
                styleTitle.BorderLeft = BorderStyle.Thin;
                styleTitle.BorderRight = BorderStyle.Thin;
                styleTitle.FillBackgroundColor = HSSFColor.Green.Index;
                styleTitle.FillPattern = FillPattern.SolidForeground;
                styleTitle.FillForegroundColor = HSSFColor.Green.Index;

                var font1 = templateWorkbook.CreateFont();
                font1.FontHeightInPoints = 11;
                font1.FontName = "Calibri";
                font1.Boldweight = (short)NPOI.SS.UserModel.FontBoldWeight.Bold;
                font1.Color = (short)NPOI.SS.UserModel.FontColor.Red;

                ICellStyle style2 = templateWorkbook.CreateCellStyle();
                style2.SetFont(font1);

                //List<View_TeamOutletNotAssign> listNotAssign = new List<View_TeamOutletNotAssign>();
                //List<Outlet> listOutlet = new List<Outlet>();
                //listNotAssign = Business.User.getTeamOutletNotAssign(User.ProjectID, User.OutletTypeID);
                //listOutlet = Outlet.getByProjectAndType(User.ProjectID, User.OutletTypeID);
                HSSFSheet sheetChanel = templateWorkbook.GetSheet("Chanel") as HSSFSheet;
                HSSFSheet sheetRegion = templateWorkbook.GetSheet("Region") as HSSFSheet;
                HSSFSheet sheetGroup = templateWorkbook.GetSheet("Group") as HSSFSheet;
                HSSFSheet sheetPromotion = templateWorkbook.GetSheet("Promotion") as HSSFSheet;
                HSSFSheet sheetBrand = templateWorkbook.GetSheet("Brand") as HSSFSheet;

                //excel data teamoutlet
                int x = 1;
                int u = 2;

                IRow rowTitleChanel = sheetChanel.CreateRow(x);
                rowTitleChanel.Height = 500;
                rowTitleChanel.CreateCell(1).SetCellValue("ID");
                rowTitleChanel.CreateCell(2).SetCellValue("Description");
                rowTitleChanel.GetCell(1).CellStyle = styleTitle;
                rowTitleChanel.GetCell(2).CellStyle = styleTitle;
                for (int i = 0; i < listChanel.Count(); i++)
                {

                    IRow row = sheetChanel.CreateRow(u);
                    row.CreateCell(1).SetCellValue(listChanel[i].ID);
                    row.CreateCell(2).SetCellValue(listChanel[i].ChanelName);
                    u++;
                }
                u = 2;

                IRow rowTitleRegion = sheetRegion.CreateRow(x);
                rowTitleRegion.Height = 500;
                rowTitleRegion.CreateCell(1).SetCellValue("ID");
                rowTitleRegion.CreateCell(2).SetCellValue("Description");
                rowTitleRegion.GetCell(1).CellStyle = styleTitle;
                rowTitleRegion.GetCell(2).CellStyle = styleTitle;
                for (int i = 0; i < listRegion.Count(); i++)
                {

                    IRow row = sheetRegion.CreateRow(u);
                    row.CreateCell(1).SetCellValue(listRegion[i].ID);
                    row.CreateCell(2).SetCellValue(listRegion[i].RegionName);
                    u++;
                }
                u = 2;

                IRow rowTitleGroup = sheetGroup.CreateRow(x);
                rowTitleGroup.Height = 500;
                rowTitleGroup.CreateCell(1).SetCellValue("ID");
                rowTitleGroup.CreateCell(2).SetCellValue("Name");
                rowTitleGroup.CreateCell(3).SetCellValue("Description");
                rowTitleGroup.GetCell(1).CellStyle = styleTitle;
                rowTitleGroup.GetCell(2).CellStyle = styleTitle;
                rowTitleGroup.GetCell(3).CellStyle = styleTitle;
                for (int i = 0; i < listGroup.Count(); i++)
                {

                    IRow row = sheetGroup.CreateRow(u);
                    row.CreateCell(1).SetCellValue(listGroup[i].ID);
                    row.CreateCell(2).SetCellValue(listGroup[i].GroupCode);
                    row.CreateCell(3).SetCellValue(listGroup[i].GroupName);
                    u++;
                }
                u = 2;

                IRow rowTitlePromotion = sheetPromotion.CreateRow(x);
                rowTitlePromotion.Height = 500;
                rowTitlePromotion.CreateCell(1).SetCellValue("Value");
                rowTitlePromotion.CreateCell(2).SetCellValue("Description");
                rowTitlePromotion.GetCell(1).CellStyle = styleTitle;
                rowTitlePromotion.GetCell(2).CellStyle = styleTitle;
                IRow rowKM1 = sheetPromotion.CreateRow(u);
                rowKM1.CreateCell(1).SetCellValue("TRUE");
                rowKM1.CreateCell(2).SetCellValue("Chạy khuyến mãi đổi quà tặng");
                u++;
                IRow rowKM2 = sheetPromotion.CreateRow(u);
                rowKM2.CreateCell(1).SetCellValue("FALSE");
                rowKM2.CreateCell(2).SetCellValue("Không chạy khuyến mãi đổi quà tặng");

                u = 2;


                IRow rowTitleBrand = sheetBrand.CreateRow(x);
                rowTitleBrand.Height = 500;
                rowTitleBrand.CreateCell(1).SetCellValue("ID");
                rowTitleBrand.CreateCell(2).SetCellValue("Description");
                rowTitleBrand.GetCell(1).CellStyle = styleTitle;
                rowTitleBrand.GetCell(2).CellStyle = styleTitle;
                for (int i = 0; i < listBrand.Count(); i++)
                {

                    IRow row = sheetBrand.CreateRow(u);
                    row.CreateCell(1).SetCellValue(listBrand[i].ID);
                    row.CreateCell(2).SetCellValue(listBrand[i].BrandName);
                    u++;
                }
                u = 2;

                sheetChanel.ForceFormulaRecalculation = true;
                sheetRegion.ForceFormulaRecalculation = true;
                sheetGroup.ForceFormulaRecalculation = true;
                sheetPromotion.ForceFormulaRecalculation = true;
                sheetBrand.ForceFormulaRecalculation = true;
                MemoryStream output = new MemoryStream();
                string downloadFileName = "FormartOutlet" + " " + DateTime.Now.ToString("dd/MM/yyyy") + ".xls";
                templateWorkbook.Write(output);
                return File(output.ToArray(), "application/vnd.ms-excel", downloadFileName);
            }
        }

        public ActionResult Import()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                AddOutletModel model = new AddOutletModel();
                try
                {
                    string _messagerError = String.Empty;
                    string _FilePath = String.Empty;
                    string imageUrl = String.Empty;
                    string imagePath = String.Empty;
                    string imageName = String.Empty;
                    string Link = String.Empty;
                    ISheet sheet = null;

                    imageName = Request.Files[0].FileName;
                    Business.Connection.CreateImagePathWeb(Request.PhysicalApplicationPath, Request.Url.Authority, "FILEOUTLET", _FilePath, out imageUrl);
                    imagePath = Request.PhysicalApplicationPath + "/FILEOUTLET/" + _FilePath;

                    Directory.CreateDirectory(imagePath);

                    if (System.IO.File.Exists(imagePath + "/" + imageName))
                    {
                        imageName = "exist" + Common.CodeMD5.MD5Hash(DateTime.Now.ToString("dd/MM/yyyy hh:mm:ss ttt")) + imageName;
                    }

                    Request.Files[0].SaveAs(imagePath + "/" + imageName);

SP19/Report/Views/AddOutletTeam/Index.cshtml
@model Report.Models.AddOutletModel
@{
    ViewBag.Title = "Thêm Oultet";
}

<div class="m-content">

    <div class="row">
        <div class="col-md-12">
            <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
                <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text" style="color:white">
                                Chọn file import
                            </h3>
                        </div>
                    </div>
                </div>
                <form class="m-form m-form--fit m-form--label-align-right">

                    <div class="m-portlet__body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    <input type="file" id="picfile" name="picf" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="m-portlet__foot m-portlet__foot--fit">

                    <button type="button" style="background-color: #10522B;color:white" class="btn btn-success" onclick="imporFile()">Import File</button>
                    @using (Html.BeginForm("ExportFormat", "AddOutletTeam"))
                    {
                        <button type="submit" style="background-color: #10522B;color:white" class="btn btn-success">Tải File Format</button>
                    }
                </div>

            </div>
        </div>
    </div>
</div>

<div id='loadingmessage' style='display:none; text-align: -webkit-center;'>
    <img src="~/Images/process.gif" class="loader" />
</div>

<div id="layout-data">
    @{Html.RenderPartial("_List", Model);}
</div>

<script>
    function imporFile() {
        debugger;

        if (document.getElementById("picfile").files.length == 0) {
            swal("", "Chọn file import!", "error");
        }
        else if (document.getElementById("picfile").files[0].name.split(".")[1].toString() != "xls") {
            swal("", "File import phải là file Excel có đuôi .XLS và format giống file Export! Vui lòng kiểm tra lại.", "error");
        }
        else {
            $('#loadingmessage').show();
            var fileImport = document.getElementById("picfile").files[0];
            var formData = new FormData();
            formData.append("FileUpload", fileImport);
            //formData.append("orderID", orderID); // hàng công trình, hàng lẻ

            $.ajax({
                type: "POST",
                url: "@Url.Action("Import", "AddOutletTeam")",
                data: formData,
                dataType: 'html',
                contentType: false,
                processData: false,
                success: function (data) {
                    debugger;
                    $('#layout-data').html(data);
                    $('#loadingmessage').hide();
                }
            });
        }
    }

</script>

SP19/Report/Views/AddOutletTeam/_List.cshtml
@model Report.Models.AddOutletModel

@{
    var user = ViewBag.UserRole;
}

<div class="m-content" style="padding-top:0px;border-radius:10px">
    <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
        <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text" style="color:white">
                        Danh Sách Siêu Thị
                    </h3>
                </div>
            </div>
        </div>

        <div class="m-portlet__body" style="overflow:auto">
            <table class="table table-striped new" id="m_table_outlet">
                <thead style="background-color: #10522B; color: white; text-align: center">
                    <tr>
                        <th>Mã</th>
                        <th>Tên</th>
                        <th>Tỉnh/Thành</th>
                        <th>Quận/Huyện</th>
                        <th>Địa Chỉ</th>
                    </tr>
                </thead>
                <tbody style="color: white">
                    @{ foreach (var item in Model.listData)
                     {
                        <tr>
                            <td >@item.OutletCode</td>
                            <td >@item.OutletName</td>
                            <td >@item.City</td>
                            <td >@item.District</td>
                            <td >@item.OutletAddress</td>
                        </tr>
                     }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    if(@Model.status == 1){
        setTimeout(function(){
            swal("","@Model.message", "success");
        },0)
    }else if(@Model.status == 2){
        setTimeout(function(){
            swal("","@Model.message", "error");
        },0)
    }
    setTimeout(function(){
        $('#m_table_outlet').DataTable({ "ordering": false });
    },0)
</script>