SP19/Report/Controllers/ReportVongQuayController.cs
using Business;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using Report.Helpers;
using Spire.Xls;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Report.Controllers
{
    // THỐNG KÊ SỐ LẦN QUAY CÁC VÒNG QUAY THEO OUTLET 
    public class ReportVongQuayController : BaseController
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            if (User == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                string _messageError = String.Empty;
                ReportSanLuongSE se = new ReportSanLuongSE();
                List<ReportSoLanQuay> list = new List<ReportSoLanQuay>();
                ReportProduct report = new ReportProduct();
                Common.ERROR_CODE.ERROR_CODE_ITEMS_SELECT error = report.ReportSoVongQuay(ref _messageError, ref list, User.OutletTypeID, User.ProjectID, se);
                //lấy brand
                ViewBag.brand = Business.Brand.GetAll(User.ProjectID);
                return View(list);
            }
        }

        public ActionResult Search(string _dateformreport, string _datetoreport, string _cty)
        {
            //-------------------------------------------Lấy list danh Sách Report ghi ra excel
            string _messageError = String.Empty;
            ReportSanLuongSE se = new ReportSanLuongSE();
            se.DateFromReport = Common.ConvertUtils.ConvertStringToShortDate(_dateformreport);
            se.DateToReport = Common.ConvertUtils.ConvertStringToShortDate(_datetoreport);
            List<ReportSoLanQuay> list = new List<ReportSoLanQuay>();
            ReportProduct report = new ReportProduct();
            Common.ERROR_CODE.ERROR_CODE_ITEMS_SELECT error = report.ReportSoVongQuay(ref _messageError, ref list, int.Parse(_cty), User.ProjectID, se);
            //lấy brand
            ViewBag.brand = Business.Brand.GetAll(User.ProjectID);
            return PartialView("_List", list);
        }        
    }
}

SP19/Report/Views/ReportVongQuay/Index.cshtml
@model List<Business.ReportSoLanQuay>
    @{
        ViewBag.Title = "Report Admin";
    }
    <div>
        @{Html.RenderPartial("_Search", new Business.ReportSanLuongSE());}
    </div> 
    <div id="vongquay">
    @{Html.RenderPartial("_List", Model);}
</div>

SP19/Report/Views/ReportVongQuay/_List.cshtml
@model List<Business.ReportSoLanQuay>

@{
    ViewBag.Title = "Notification";
    string user = ViewBag.RoleUser;
    List<Business.Brand> brand = ViewBag.brand;
    int number = brand.Count() + 1;
}
<style>
    a:not([href]):not([tabindex]) {
        color: #10522b;
        text-decoration: underline;
        cursor: pointer;
    }
</style>

<div class="m-content" style="padding-top:0px;border-radius:10px">
    <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
        <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text" style="color:white">
                        Nội Dung Báo Cáo
                    </h3>
                </div>
            </div>
        </div>

        <div class="m-portlet__body" style="overflow:auto">
            <table class="table table-striped new" id="m_table_notification">
                <thead style="background-color: #10522B; color: white; text-align: center">
                    <tr>
                        <th rowspan="2" style="width: 200px; border: 1px solid #eee">Siêu Thị</th>
                        <th colspan="@number" style="width: 200px; border: 1px solid #eee">Số Lần Quay</th>
                        <th rowspan="2" style="border: 1px solid #eee">

                        </th>

                    </tr>
                    <tr style="color: white; background-color: #10522B;color:white">
                        @{foreach (var e in brand)
                        {
                            <th style="border: 1px solid #eee">@e.BrandName</th>
                        }
                        }
                        <th style="border: 1px solid #eee">Mega</th>
                    </tr>
                </thead>
                <tbody style="color: white">
                    @{ foreach (var item in Model)
                     {
                        <tr>
                            <td>@item.OutletName</td>
                            @for (int i = 0; i < brand.Count(); i++)
                            {
                                var simple = item.list.Where(p => p.BranID == brand[i].ID);
                                if (simple.Count() > 0)
                                {
                                    <td>@simple.FirstOrDefault().Number</td>
                                }
                                else
                                {
                                    <td></td>
                                }

                            }
                            @if (item.list.Where(p => p.BranID == 0).Count() > 0)
                            {
                                <td>@item.list.Where(p => p.BranID == 0).FirstOrDefault().Number</td>
                            }
                            else
                            {
                                <td></td>
                            }
                            <td>
                                @item.Total
                            </td>
                        </tr>
                     }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    var table = $('#m_table_notification').DataTable({ "ordering": false });
    function getCheckedBoxes(chkboxName) {
        var checkboxes = document.getElementsByName(chkboxName);
        var checkboxesChecked = [];
        // loop over them all
        for (var i = 0; i < checkboxes.length; i++) {
            // And stick the checked ones onto an array...
            if (checkboxes[i].checked) {
                checkboxesChecked.push(checkboxes[i].value);
            }
        }
        // Return the array if it is non-empty, or null
        return checkboxesChecked.length > 0 ? checkboxesChecked : null;
    }

    // Call as
    function NotificationDetail(IDNotification) {
        debugger;
        $.ajax({
            type: "GET",
            url: '@Url.Action("Detail")',
            data: { _NotificationID: IDNotification },
            datatype: "image/jpg",
            success: function (data) {
                if (data.ok == false) {
                    window.location = data.newurl;
                }
                else {
                    $('#myModal').empty();
                    $('#myModal').append(data);
                    $('#myModal').modal('show');
                }
            }
        });
    }
    function UpdateNotification() {
        debugger;
        var checkedBoxes = getCheckedBoxes("idnotification").join('|');
        $('#myModal').modal('hide');
        $('#loadingmessage').show();
        $.ajax({
            url: "@Url.Action("Update", "Notification")",
            type: 'GET',
            data: { _listIDNotification: checkedBoxes },
            contentType: 'application/json; charset=utf-8',
            datatype: 'html',
            success: function (result) {
                debugger;
                if (result.ok == false) {
                    window.location = result.newurl;
                }
                else {
                    $('#listnotification').html(result);
                    $('#loadingmessage').hide();
                }

            }
        });
    }
</script>

SP19/Report/Views/ReportVongQuay/_Search.cshtml
@model Business.ReportSanLuongSE
@{
    Layout = null;
}

<div class="m-content">

    <div class="row">
        <div class="col-md-12">
            <div class="m-portlet m-portlet--mobile" style="border-radius:10px">
                <div class="m-portlet__head" style="background-color: #10522B; border-radius: 10px 10px 0px 0px;border:2px solid white">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text" style="color:white">
                                Nội Dung Tìm Kiếm
                            </h3>
                        </div>
                    </div>
                </div>
                <form class="m-form m-form--fit m-form--label-align-right">

                    <div class="m-portlet__body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    @Html.LabelFor(m => m.DateFromReport)
                                    @Html.TextBoxFor(m => m.DateFromReport, "{0:dd/MM/yyyy}", new { style = "width:100%" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-form__group">
                                    @Html.LabelFor(m => m.DateToReport)
                                    @Html.TextBoxFor(m => m.DateToReport, "{0:dd/MM/yyyy}", new { style = "width:100%" })
                                </div>
                            </div>
                            <div class="col-md-6" style="margin-top:2%">
                                <div class="form-group m-form__group">
                                    Tên Siêu Thị
                                    <select class="chosen-select" id="typevongquay" name="typevongquay" style="width:300px">
                                        <option value="1">P2P</option>
                                        <option value="2">Delta</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <button type="button" style="background-color: #10522B;color:white" class="btn btn-success" onclick="SearchVongQuay()">Tìm Kiếm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $("#DateFromReport").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy'
    });
    $("#DateToReport").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy'
    });
</script>
<script type="text/javascript" src="~/Scripts/customdatevalidation.js"></script>
<link rel="stylesheet" href="~/Content/chosen.css" />
<script src="~/Scripts/chosen.jquery.js"></script>
<script src="~/Scripts/chosen.proto.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $(".chosen-select").chosen();
        $(".chosen-container").css("width", "100%");
        $(".chosen-container").css("height", "30px!important");
    });
</script>

<script>

    var x = 0;
    function SearchVongQuay() {
        debugger;
        var _cty = $("#typevongquay").val();
        var _dateformreport = $("#DateFromReport").val();
        var _datetoreport = $("#DateToReport").val();
        $('#loading').css("display", "block");

        $.ajax({
            url: "@Url.Action("Search", "ReportVongQuay")",
            type: 'GET',
            data: { _dateformreport: _dateformreport, _datetoreport: _datetoreport, _cty: _cty },
            contentType: 'application/json; charset=utf-8',
            datatype: 'html',
            success: function (result) {
                debugger; if (result.ok == false) {
                    window.location = result.newurl;
                }
                else {
                    $('#vongquay').html(result);
                    $('#loading').css("display", "none");
                }
            }
        });
    }
</script>